version: "3.8"
services:
  fhem:
    image: ghcr.io/fhem/fhem-docker:5-bookworm
    container_name: fhem
    restart: unless-stopped
    network_mode: host
    volumes:
      - fhem-data:/opt/fhem
    environment:
      - TZ=Europe/Berlin

volumes:
  fhem-data:
    name: fhem-data
