version: "3.7"

services:
  fhem:
    image: ghcr.io/fhem/fhem-docker:5-bookworm
    container_name: fhem
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - fhem-data:/opt/fhem
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    privileged: true

volumes:
  fhem-data:
